# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constC1 <- function(p) {
    .Call('_ktaucenters_constC1', PACKAGE = 'ktaucenters', p)
}

constC2 <- function(p) {
    .Call('_ktaucenters_constC2', PACKAGE = 'ktaucenters', p)
}

my_median <- function(x) {
    .Call('_ktaucenters_my_median', PACKAGE = 'ktaucenters', x)
}

rhoAux <- function(x, cc) {
    .Call('_ktaucenters_rhoAux', PACKAGE = 'ktaucenters', x, cc)
}

rhoOpt_pablo <- function(x, cc) {
    .Call('_ktaucenters_rhoOpt_pablo', PACKAGE = 'ktaucenters', x, cc)
}

psiAux <- function(x, cc) {
    .Call('_ktaucenters_psiAux', PACKAGE = 'ktaucenters', x, cc)
}

psiOpt_pablo <- function(x, cc) {
    .Call('_ktaucenters_psiOpt_pablo', PACKAGE = 'ktaucenters', x, cc)
}

derpsiAux <- function(x, cc) {
    .Call('_ktaucenters_derpsiAux', PACKAGE = 'ktaucenters', x, cc)
}

derpsiOpt_pablo <- function(x, cc) {
    .Call('_ktaucenters_derpsiOpt_pablo', PACKAGE = 'ktaucenters', x, cc)
}

normal_consistency_constants <- function(p) {
    .Call('_ktaucenters_normal_consistency_constants', PACKAGE = 'ktaucenters', p)
}

constC1 <- function(p) {
    .Call('_ktaucenters_constC1', PACKAGE = 'ktaucenters', p)
}

constC2 <- function(p) {
    .Call('_ktaucenters_constC2', PACKAGE = 'ktaucenters', p)
}

my_median <- function(x) {
    .Call('_ktaucenters_my_median', PACKAGE = 'ktaucenters', x)
}

Mscale_pablo <- function(u, b, cc) {
    .Call('_ktaucenters_Mscale_pablo', PACKAGE = 'ktaucenters', u, b, cc)
}

